apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-devops-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-devops-app

  template:
    metadata:
      labels:
        app: ai-devops-app

    spec:
      containers:
        - name: ai-devops-container

          image: ai-devops-app:v1

          imagePullPolicy: Never

          ports:
            - containerPort: 8000