name: FastAPI CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
   test-build-push-update-gitops:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout APP Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run Tests
        run: |
          pytest

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -f docker/app.Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/ai-devops-app:${IMAGE_TAG} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ai-devops-app:${IMAGE_TAG}

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/ai-devops-platform-gitops
          token: ${{ secrets.GHCR_TOKEN }}
          path: gitops-repo

      - name: Update GitOps Image Tag
        run: |
          cd gitops-repo
          sed -i "s|image: ghcr.io/${{ github.repository_owner }}/ai-devops-app:.*|image: ghcr.io/${{ github.repository_owner }}/ai-devops-app:${IMAGE_TAG}|g" apps/app-deployment.yaml

      - name: Commit and Push GitOps Update
        run: |
          cd gitops-repo
          git config user.name "yu900701"
          git config user.email "kd123456525@gmail.com"
          git add apps/app-deployment.yaml
          git commit -m "update ai-devops-app image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push